language: ruby

rvm: 2.2.3

sudo: false

cache:
  apt: true
addons:
  apt_packages:
  - bc

script:
- bundle exec rubocop
- bundle exec rspec spec
- bundle exec chirp

after_failure: bundle exec chirp dumplogs ./log

notifications:
  webhooks:
    urls:
    - 'https://chirp-tracker-production.herokuapp.com/travis'
    on_success: always
    on_failure: never
