language: ruby
rvm: 2.2.0
sudo: false
cache:
  apt: true
addons:
  apt_packages:
  - bc
script: bundle exec chirp
after_success: ./bin/pushback &>/dev/null
after_failure: ./bin/dumplogs ./log
notifications:
  webhooks:
    urls:
    - 'https://chirp-tracker-production.herokuapp.com/travis'
    on_success: always
    on_failure: never
